### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Stvad** [lukesmurray/scrawl#1]
Hey! Thanks for building this! 
It looks really exciting 🙂.  

It'd be great if there were a FF support for this! 
I think with the WebExtensions API it should be fairly easy to support both with the same code (though it doesn't cover the full suit of Chrome APIs afaik)

**Comment by lukesmurray** [comment]
firefox submitted and coming soon. will be available at this url https://addons.mozilla.org/en-US/firefox/addon/scrawly/

**Comment by lukesmurray** [comment]
Firefox extension is up https://addons.mozilla.org/en-US/firefox/addon/scrawly/
