### ISSUE TITLE
[Contributing] How to help?

### ISSUE THREAD

**Issue by AsterYujano** [lukesmurray/scrawl#7]
Hello! Is there a Roadmap or something for this project? 

I would love to contribute, just discovered it and it is sooooo good :)

**Comment by lukesmurray** [comment]
Thanks for asking! Contributing on this project is very casual. I can help put together instructions for running the project locally if you're having any issues. There is no roadmap at the moment. But feel free to propose features and we could make one. I'm also absolutely happy to accept pull requests. To increase the likelihood of the pr getting accepted we could discuss new features/ideas before you start writing code but if you have a PR ready to go then definitely share it 🎉.

**Comment by AsterYujano** [comment]
I noticed few bugs, gonna do PRs for them when I have time :)

**Comment by lukesmurray** [comment]
That sounds good to me. Feel free to report bugs as issues as well so that we can all contribute fixes. I will close this issue out for now since any bugs/features should probably be associated with their own issue.
